name: stat-card
run-name: ${{ github.workflow }} ✅ ${{ github.ref }} ✅ ${{ github.actor }} ✅ ${{ github.event_name}}
on:
  workflow_dispatch:

jobs:

  Card:
    name: Card
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: 3
    runs-on: ubuntu-latest
    permissions: write-all
    timeout-minutes: 10
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
      GITHUB_owner: ${{github.repository_owner}}
      FORCE_COLOR: true
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}

    steps:

    - name: checkout ${{ github.ref }}
      id: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    # - run: echo "::add-mask::$GITHUB_owner"

    - name: node
      id: node
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: npm
      id: npm
      run: |
       npm install --save

    - name: update
      id: update
      run: |
       npm run update

    - name: check
      id: check
      run: |
       ls -lh ${{ github.workspace }}/generated
       cat ${{ github.workspace }}/generated/overview.svg
       cat ${{ github.workspace }}/generated/languages.svg
       unset GITHUB_TOKEN

    - name: upload to gist
      id: upload
      working-directory: ${{ github.workspace }}/generated
      run: |
       unset GITHUB_TOKEN
       echo ${{secrets.ACCESS_TOKEN}} | gh auth login --with-token
       count=$(gh api gists --jq length)
       echo $count
       gh auth status
       gh gist edit d2bbea83df4837dbecd89974400cc1a8 -f overview.svg overview.svg
       # cat overview.svg | gh gist create overview.svg

    - name: E-build & shell-x@v0.3
      id: shell
      if: ${{ runner.os != 'Linux' }}
      uses: milankomaj/shell-x@v0.3
      with:
        shell: bash
        locale: sk_SK.utf8
        timezone: Europe/Bratislava
        comand:
          sed -i '4d' ${{ github.workspace }}/updater.js &&
          npm run E-build &&
          rm -r ${{ github.workspace }}/node_modules &&
          node ./dist/esbuild_updater.js ${{github.repository_owner}} -info &&
          ls -slh ${{ github.workspace }}/dist &&
          ls -slh ${{ github.workspace }}/generated &&
          cat ${{ github.workspace }}/generated/overview.svg &&
          cat ${{ github.workspace }}/generated/languages.svg